name: Bug report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
  - type: textarea
    attributes:
      label: Steps to reproduce
  - type: textarea
    attributes:
      label: Logs / screenshots
  - type: input
    attributes:
      label: Version
